# Generated by Django 3.0.3 on 2020-05-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contributers', models.TextField(max_length=200)),
                ('iswc', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('item_id', models.BigIntegerField()),
            ],
        ),
    ]
