# Generated by Django 3.0.5 on 2020-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalwork',
            name='contributers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='musicalwork',
            name='item_id',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='musicalwork',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='musicalwork',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
