# Generated by Django 3.0.5 on 2020-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200504_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalwork',
            name='iswc',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
