# Generated by Django 3.0.5 on 2020-05-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200504_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicalwork',
            old_name='contributers',
            new_name='contributors',
        ),
    ]
