# Generated by Django 3.0.5 on 2020-05-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200505_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalwork',
            name='iswc',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
