# Generated by Django 3.0.5 on 2020-05-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200505_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalwork',
            name='item_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
